### ISSUE TITLE
low level of GNSS reception on 20200110 T-Motion

### ISSUE THREAD

**Issue by NOWherers** [Xinyuan-LilyGO/LilyGO-T-Motion#1]
I have two boards branded with T-Motion 20200110.
One of them uses the built-in gnss antenna and the other one uses an antenna from a T-Beam board.

I wrote a sketch to pass the gnss messages directly to the com port to use the ublox u-center software to see whats going on with the gnss receiver.

unfortunately i get barely any signals, just 3-15db and just for a few seconds from one sattelite and ocaisonally from two sattelites for a few seconds.
I have several gnss receivers and have no problem to receive multiple sattelites with them...sometimes it takes a few minutes but the behaiviour doesnt change with the acsip s76g/sony cxd5603 even after hours.

Is there a Problem in the revision of the board? Any ideas?

**Comment by PetrJoch** [comment]
I have same issue. I confirmed boar revision Issue. Board is defective. Serious problem with gnss receiver acsip s76g/sony cxd5603 never sent GPS possition even after hours.

**Comment by lewisxhe** [comment]
The front-end time has been restored to normal due to problems with the purchased raw materials. If you have any questions, you can contact the sales customer service for after-sales processing.
